StartupEvents.registry('block', e => {
    e.create('potted_sugar_cane')
    .tagBlock('minecraft:flower_pots').model('playingwithfire:flowerpots/potted_sugar_cane')
    .fullBlock(false)
    .renderType('cutout')
    .box(5, 0, 5, 11, 6, 11)
    .hardness(0)
    .resistance(0)
    e.create('potted_twisting_vines').tagBlock('minecraft:flower_pots').model('playingwithfire:flowerpots/potted_twisting_vines')
    .fullBlock(false)
    .renderType('cutout')
    .box(5, 0, 5, 11, 6, 11)
    .hardness(0)
    .resistance(0)
})